import { defineStore } from 'pinia';
import { ref } from 'vue';

export const useParentStore = defineStore('parent', () => {
  const parents = ref([
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      id: 'P001',
      firstname: 'John',
      lastname: 'Doe',
      gender: 'Male',
      student_id: ['0001', '0002'],
      address: '123 Oak St',
      dob: '1970-04-10',
      mobile_no: '08123456701',
      email: 'john.doe@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      id: 'P002',
      firstname: 'Jane',
      lastname: 'Smith',
      gender: 'Female',
      student_id: ['0003'],
      address: '456 Maple St',
      dob: '1975-07-15',
      mobile_no: '08123456702',
      email: 'jane.smith@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      id: 'P003',
      firstname: 'Michael',
      lastname: 'Johnson',
      gender: 'Male',
      student_id: ['0004', '0005'],
      address: '789 Pine St',
      dob: '1972-05-20',
      mobile_no: '08123456703',
      email: 'michael.johnson@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      id: 'P004',
      firstname: 'Laura',
      lastname: 'Williams',
      gender: 'Female',
      student_id: ['0006'],
      address: '101 Birch St',
      dob: '1980-09-25',
      mobile_no: '08123456704',
      email: 'laura.williams@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      id: 'P005',
      firstname: 'David',
      lastname: 'Brown',
      gender: 'Male',
      student_id: ['0007', '0008'],
      address: '102 Cedar St',
      dob: '1978-11-18',
      mobile_no: '08123456705',
      email: 'david.brown@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      id: 'P006',
      firstname: 'Emily',
      lastname: 'Jones',
      gender: 'Female',
      student_id: ['0009'],
      address: '103 Oak St',
      dob: '1982-03-14',
      mobile_no: '08123456706',
      email: 'emily.jones@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      id: 'P007',
      firstname: 'Robert',
      lastname: 'Garcia',
      gender: 'Male',
      student_id: ['0010'],
      address: '104 Maple St',
      dob: '1976-07-30',
      mobile_no: '08123456707',
      email: 'robert.garcia@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      id: 'P008',
      firstname: 'Sarah',
      lastname: 'Martinez',
      gender: 'Female',
      student_id: ['0011', '0012'],
      address: '105 Pine St',
      dob: '1979-02-11',
      mobile_no: '08123456708',
      email: 'sarah.martinez@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      id: 'P009',
      firstname: 'James',
      lastname: 'Lopez',
      gender: 'Male',
      student_id: ['0013'],
      address: '106 Fir St',
      dob: '1983-05-08',
      mobile_no: '08123456709',
      email: 'james.lopez@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      id: 'P010',
      firstname: 'Lisa',
      lastname: 'Clark',
      gender: 'Female',
      student_id: ['0014', '0015'],
      address: '107 Cedar St',
      dob: '1981-12-20',
      mobile_no: '08123456710',
      email: 'lisa.clark@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      id: 'P011',
      firstname: 'Daniel',
      lastname: 'Lewis',
      gender: 'Male',
      student_id: ['0016'],
      address: '108 Oak St',
      dob: '1974-06-22',
      mobile_no: '08123456711',
      email: 'daniel.lewis@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      id: 'P012',
      firstname: 'Karen',
      lastname: 'Walker',
      gender: 'Female',
      student_id: ['0017', '0018'],
      address: '109 Maple St',
      dob: '1985-10-10',
      mobile_no: '08123456712',
      email: 'karen.walker@example.com',
    },
  ]);

  const get_parent_or_404 = (id: string) => {
    return parents.value.find((parent) => parent.id === id) ?? '404';
  };

  return {
    parents,
    get_parent_or_404,
  };
});
