/* eslint-disable @typescript-eslint/no-explicit-any */
import { defineStore } from 'pinia';
import { ref } from 'vue';

export type searchParams = string | null;

export const useStudentStore = defineStore('students', () => {
  const students = ref([
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      reg_no: '0001',
      firstname: 'John',
      lastname: 'Doe',
      gender: 'Male',
      parent_id: 'P001',
      class: 'JSS1',
      section: 'A',
      sport_house: 'Red',
      department: 'Science',
      subjects: [
        'English',
        'Mathematics',
        'Physics',
        'Biology',
        'Chemistry',
        'Geography',
        'Computer',
        'Civic',
        'Islamic Religious Studies',
      ],
      address: '123 Main St',
      dob: '2008-05-10',
      mobile_no: '08123456701',
      email: 'john.doe@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      reg_no: '0002',
      firstname: 'Jane',
      lastname: 'Smith',
      gender: 'Female',
      parent_id: 'P002',
      class: 'JSS1',
      section: 'B',
      sport_house: 'Blue',
      department: 'Art',
      subjects: [
        'English',
        'Mathematics',
        'Literature in English',
        'Government',
        'Christian Religious Studies',
        'Geography',
        'Civic',
        'Yoruba',
        'General Studies',
      ],
      address: '456 Oak St',
      dob: '2008-08-15',
      mobile_no: '08123456702',
      email: 'jane.smith@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      reg_no: '0003',
      firstname: 'Michael',
      lastname: 'Johnson',
      gender: 'Male',
      parent_id: 'P003',
      class: 'JSS2',
      section: 'A',
      sport_house: 'Yellow',
      department: 'Commercial',
      subjects: [
        'English',
        'Mathematics',
        'Government',
        'Commerce',
        'Economics',
        'Civic',
        'Computer',
        'Hausa',
        'General Studies',
      ],
      address: '789 Maple St',
      dob: '2007-11-22',
      mobile_no: '08123456703',
      email: 'michael.johnson@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      reg_no: '0004',
      firstname: 'Emily',
      lastname: 'Brown',
      gender: 'Female',
      parent_id: 'P004',
      class: 'JSS2',
      section: 'B',
      sport_house: 'White',
      department: 'Engineering',
      subjects: [
        'English',
        'Mathematics',
        'Physics',
        'Biology',
        'Chemistry',
        'Computer',
        'Geography',
        'Igbo',
        'General Studies',
      ],
      address: '101 Birch St',
      dob: '2007-09-05',
      mobile_no: '08123456704',
      email: 'emily.brown@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      reg_no: '0005',
      firstname: 'James',
      lastname: 'Jones',
      gender: 'Male',
      parent_id: 'P005',
      class: 'JSS3',
      section: 'C',
      sport_house: 'Green',
      department: 'Science',
      subjects: [
        'English',
        'Mathematics',
        'Physics',
        'Biology',
        'Chemistry',
        'Geography',
        'Computer',
        'Civic',
        'Islamic Religious Studies',
      ],
      address: '102 Cedar St',
      dob: '2006-04-19',
      mobile_no: '08123456705',
      email: 'james.jones@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      reg_no: '0006',
      firstname: 'Sarah',
      lastname: 'Garcia',
      gender: 'Female',
      parent_id: 'P006',
      class: 'SS1',
      section: 'A',
      sport_house: 'Red',
      department: 'Art',
      subjects: [
        'English',
        'Mathematics',
        'Literature in English',
        'Government',
        'Christian Religious Studies',
        'Geography',
        'Civic',
        'Yoruba',
        'General Studies',
      ],
      address: '103 Pine St',
      dob: '2005-07-21',
      mobile_no: '08123456706',
      email: 'sarah.garcia@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      reg_no: '0007',
      firstname: 'David',
      lastname: 'Martinez',
      gender: 'Male',
      parent_id: 'P007',
      class: 'SS1',
      section: 'B',
      sport_house: 'Blue',
      department: 'Commercial',
      subjects: [
        'English',
        'Mathematics',
        'Government',
        'Commerce',
        'Economics',
        'Civic',
        'Computer',
        'Hausa',
        'General Studies',
      ],
      address: '104 Elm St',
      dob: '2005-10-30',
      mobile_no: '08123456707',
      email: 'david.martinez@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      reg_no: '0008',
      firstname: 'Jessica',
      lastname: 'Lee',
      gender: 'Female',
      parent_id: 'P008',
      class: 'SS2',
      section: 'A',
      sport_house: 'Yellow',
      department: 'Science',
      subjects: [
        'English',
        'Mathematics',
        'Physics',
        'Biology',
        'Chemistry',
        'Geography',
        'Computer',
        'Civic',
        'Islamic Religious Studies',
      ],
      address: '105 Spruce St',
      dob: '2004-12-25',
      mobile_no: '08123456708',
      email: 'jessica.lee@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      reg_no: '0009',
      firstname: 'Daniel',
      lastname: 'Clark',
      gender: 'Male',
      parent_id: 'P009',
      class: 'SS2',
      section: 'B',
      sport_house: 'White',
      department: 'Engineering',
      subjects: [
        'English',
        'Mathematics',
        'Physics',
        'Biology',
        'Chemistry',
        'Computer',
        'Geography',
        'Igbo',
        'General Studies',
      ],
      address: '106 Fir St',
      dob: '2004-03-03',
      mobile_no: '08123456709',
      email: 'daniel.clark@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      reg_no: '0010',
      firstname: 'Laura',
      lastname: 'Lewis',
      gender: 'Female',
      parent_id: 'P010',
      class: 'SS3',
      section: 'C',
      sport_house: 'Green',
      department: 'Art',
      subjects: [
        'English',
        'Mathematics',
        'Literature in English',
        'Government',
        'Christian Religious Studies',
        'Geography',
        'Civic',
        'Yoruba',
        'General Studies',
      ],
      address: '107 Ash St',
      dob: '2003-05-15',
      mobile_no: '08123456710',
      email: 'laura.lewis@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      reg_no: '0011',
      firstname: 'Robert',
      lastname: 'Walker',
      gender: 'Male',
      parent_id: 'P011',
      class: 'SS3',
      section: 'A',
      sport_house: 'Red',
      department: 'Science',
      subjects: [
        'English',
        'Mathematics',
        'Physics',
        'Biology',
        'Chemistry',
        'Geography',
        'Computer',
        'Civic',
        'Islamic Religious Studies',
      ],
      address: '108 Cedar St',
      dob: '2003-10-10',
      mobile_no: '08123456711',
      email: 'robert.walker@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      reg_no: '0012',
      firstname: 'Samantha',
      lastname: 'Hall',
      gender: 'Female',
      parent_id: 'P012',
      class: 'JSS1',
      section: 'C',
      sport_house: 'Blue',
      department: 'Commercial',
      subjects: [
        'English',
        'Mathematics',
        'Government',
        'Commerce',
        'Economics',
        'Civic',
        'Computer',
        'Hausa',
        'General Studies',
      ],
      address: '109 Cherry St',
      dob: '2008-01-20',
      mobile_no: '08123456712',
      email: 'samantha.hall@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      reg_no: '0013',
      firstname: 'Olivia',
      lastname: 'Allen',
      gender: 'Female',
      parent_id: 'P013',
      class: 'JSS1',
      section: 'A',
      sport_house: 'Yellow',
      department: 'Art',
      subjects: [
        'English',
        'Mathematics',
        'Literature in English',
        'Government',
        'Christian Religious Studies',
        'Geography',
        'Civic',
        'Yoruba',
        'General Studies',
      ],
      address: '110 Maple St',
      dob: '2008-06-11',
      mobile_no: '08123456713',
      email: 'olivia.allen@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      reg_no: '0014',
      firstname: 'William',
      lastname: 'Young',
      gender: 'Male',
      parent_id: 'P014',
      class: 'JSS2',
      section: 'B',
      sport_house: 'White',
      department: 'Engineering',
      subjects: [
        'English',
        'Mathematics',
        'Physics',
        'Biology',
        'Chemistry',
        'Computer',
        'Geography',
        'Igbo',
        'General Studies',
      ],
      address: '111 Birch St',
      dob: '2007-09-09',
      mobile_no: '08123456714',
      email: 'william.young@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      reg_no: '0015',
      firstname: 'Sophia',
      lastname: 'Hernandez',
      gender: 'Female',
      parent_id: 'P015',
      class: 'JSS2',
      section: 'C',
      sport_house: 'Green',
      department: 'Science',
      subjects: [
        'English',
        'Mathematics',
        'Physics',
        'Biology',
        'Chemistry',
        'Geography',
        'Computer',
        'Civic',
        'Islamic Religious Studies',
      ],
      address: '112 Oak St',
      dob: '2007-03-15',
      mobile_no: '08123456715',
      email: 'sophia.hernandez@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      reg_no: '0016',
      firstname: 'Mason',
      lastname: 'King',
      gender: 'Male',
      parent_id: 'P016',
      class: 'SS1',
      section: 'A',
      sport_house: 'Red',
      department: 'Commercial',
      subjects: [
        'English',
        'Mathematics',
        'Government',
        'Commerce',
        'Economics',
        'Civic',
        'Computer',
        'Hausa',
        'General Studies',
      ],
      address: '113 Spruce St',
      dob: '2005-05-18',
      mobile_no: '08123456716',
      email: 'mason.king@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      reg_no: '0017',
      firstname: 'Ava',
      lastname: 'Lopez',
      gender: 'Female',
      parent_id: 'P017',
      class: 'SS1',
      section: 'B',
      sport_house: 'Blue',
      department: 'Art',
      subjects: [
        'English',
        'Mathematics',
        'Literature in English',
        'Government',
        'Christian Religious Studies',
        'Geography',
        'Civic',
        'Yoruba',
        'General Studies',
      ],
      address: '114 Fir St',
      dob: '2005-10-22',
      mobile_no: '08123456717',
      email: 'ava.lopez@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      reg_no: '0018',
      firstname: 'Ethan',
      lastname: 'Scott',
      gender: 'Male',
      parent_id: 'P018',
      class: 'SS2',
      section: 'A',
      sport_house: 'Yellow',
      department: 'Engineering',
      subjects: [
        'English',
        'Mathematics',
        'Physics',
        'Biology',
        'Chemistry',
        'Computer',
        'Geography',
        'Igbo',
        'General Studies',
      ],
      address: '115 Pine St',
      dob: '2004-04-02',
      mobile_no: '08123456718',
      email: 'ethan.scott@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      reg_no: '0019',
      firstname: 'Mia',
      lastname: 'Green',
      gender: 'Female',
      parent_id: 'P019',
      class: 'SS2',
      section: 'B',
      sport_house: 'White',
      department: 'Science',
      subjects: [
        'English',
        'Mathematics',
        'Physics',
        'Biology',
        'Chemistry',
        'Geography',
        'Computer',
        'Civic',
        'Islamic Religious Studies',
      ],
      address: '116 Cedar St',
      dob: '2004-09-30',
      mobile_no: '08123456719',
      email: 'mia.green@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      reg_no: '0020',
      firstname: 'Lucas',
      lastname: 'Adams',
      gender: 'Male',
      parent_id: 'P020',
      class: 'SS3',
      section: 'C',
      sport_house: 'Green',
      department: 'Commercial',
      subjects: [
        'English',
        'Mathematics',
        'Government',
        'Commerce',
        'Economics',
        'Civic',
        'Computer',
        'Hausa',
        'General Studies',
      ],
      address: '117 Maple St',
      dob: '2003-06-18',
      mobile_no: '08123456720',
      email: 'lucas.adams@example.com',
    },
  ]);

  const get_student_or_404 = (reg: string) => {
    return students.value.find((student) => student.reg_no === reg) ?? '404';
  };

  const search_for_student = (searchForm: any) => {
    return students.value.filter(
      (student) =>
        (searchForm.cls == null || student.class == searchForm.cls) &&
        (searchForm.section == null || student.section == searchForm.section)
    );
  };

  return {
    students,
    get_student_or_404,
    search_for_student,
  };
});
