/* eslint-disable @typescript-eslint/no-explicit-any */
import { defineStore } from 'pinia';
import { ref } from 'vue';

export const useTeacherStore = defineStore('teachers', () => {
  const teachers = ref([
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      id: 'T001',
      firstname: 'Alice',
      lastname: 'Johnson',
      gender: 'Female',
      isAdmin: false,
      isFormTeacher: false,
      assigned_subjects: ['English', 'Literature in English'],
      class: ['JSS1', 'JSS2'],
      address: '123 Oak St',
      dob: '1985-03-12',
      mobile_no: '08012345601',
      email: 'alice.johnson@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      id: 'T002',
      firstname: 'Brian',
      lastname: 'Smith',
      gender: 'Male',
      isAdmin: false,
      isFormTeacher: false,
      assigned_subjects: ['Mathematics'],
      class: ['SS1'],
      address: '456 Maple St',
      dob: '1978-07-22',
      mobile_no: '08012345602',
      email: 'brian.smith@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      id: 'T003',
      firstname: 'Catherine',
      lastname: 'Williams',
      gender: 'Female',
      isAdmin: false,
      isFormTeacher: false,
      assigned_subjects: ['Physics', 'Chemistry'],
      class: ['SS2', 'SS3'],
      address: '789 Pine St',
      dob: '1980-05-15',
      mobile_no: '08012345603',
      email: 'catherine.williams@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      id: 'T004',
      firstname: 'David',
      lastname: 'Brown',
      gender: 'Male',
      isAdmin: false,
      isFormTeacher: false,
      assigned_subjects: ['Biology'],
      class: ['JSS3'],
      address: '101 Birch St',
      dob: '1975-11-01',
      mobile_no: '08012345604',
      email: 'david.brown@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      id: 'T005',
      firstname: 'Emma',
      lastname: 'Jones',
      gender: 'Female',
      isAdmin: false,
      isFormTeacher: false,
      assigned_subjects: ['Geography'],
      class: ['JSS2', 'JSS3'],
      address: '102 Cedar St',
      dob: '1982-08-09',
      mobile_no: '08012345605',
      email: 'emma.jones@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      id: 'T006',
      firstname: 'Frank',
      lastname: 'Garcia',
      gender: 'Male',
      isAdmin: false,
      isFormTeacher: false,
      assigned_subjects: ['Computer', 'Civic'],
      class: ['SS1', 'SS2'],
      address: '103 Oak St',
      dob: '1973-04-18',
      mobile_no: '08012345606',
      email: 'frank.garcia@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      id: 'T007',
      firstname: 'Grace',
      lastname: 'Martinez',
      gender: 'Female',
      isAdmin: false,
      isFormTeacher: false,
      assigned_subjects: ['Islamic Religious Studies'],
      class: ['SS3'],
      address: '104 Maple St',
      dob: '1976-12-25',
      mobile_no: '08012345607',
      email: 'grace.martinez@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      id: 'T008',
      firstname: 'Henry',
      lastname: 'Lopez',
      gender: 'Male',
      isAdmin: false,
      isFormTeacher: false,
      assigned_subjects: ['Christian Religious Studies'],
      class: ['JSS1', 'JSS2'],
      address: '105 Pine St',
      dob: '1983-02-14',
      mobile_no: '08012345608',
      email: 'henry.lopez@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      id: 'T009',
      firstname: 'Irene',
      lastname: 'Clark',
      gender: 'Female',
      isAdmin: false,
      isFormTeacher: false,
      assigned_subjects: ['Government', 'Economics'],
      class: ['SS1', 'SS2'],
      address: '106 Fir St',
      dob: '1988-09-11',
      mobile_no: '08012345609',
      email: 'irene.clark@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      id: 'T010',
      firstname: 'Jack',
      lastname: 'Lewis',
      gender: 'Male',
      isAdmin: false,
      isFormTeacher: false,
      assigned_subjects: ['Commerce'],
      class: ['SS2'],
      address: '107 Cedar St',
      dob: '1979-06-23',
      mobile_no: '08012345610',
      email: 'jack.lewis@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      id: 'T011',
      firstname: 'Karen',
      lastname: 'Hall',
      gender: 'Female',
      isAdmin: false,
      isFormTeacher: false,
      assigned_subjects: ['Literature in English', 'English'],
      class: ['JSS2', 'JSS3'],
      address: '108 Oak St',
      dob: '1984-11-05',
      mobile_no: '08012345611',
      email: 'karen.hall@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      id: 'T012',
      firstname: 'Leo',
      lastname: 'Young',
      gender: 'Male',
      isAdmin: false,
      isFormTeacher: false,
      assigned_subjects: ['Mathematics', 'Physics'],
      class: ['SS1', 'SS3'],
      address: '109 Maple St',
      dob: '1981-01-19',
      mobile_no: '08012345612',
      email: 'leo.young@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      id: 'T013',
      firstname: 'Megan',
      lastname: 'King',
      gender: 'Female',
      isAdmin: false,
      isFormTeacher: false,
      assigned_subjects: ['Chemistry'],
      class: ['SS2'],
      address: '110 Pine St',
      dob: '1980-07-03',
      mobile_no: '08012345613',
      email: 'megan.king@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      id: 'T014',
      firstname: 'Nathan',
      lastname: 'Allen',
      gender: 'Male',
      isAdmin: false,
      isFormTeacher: false,
      assigned_subjects: ['Biology', 'Geography'],
      class: ['JSS1', 'JSS3'],
      address: '111 Birch St',
      dob: '1987-04-26',
      mobile_no: '08012345614',
      email: 'nathan.allen@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      id: 'T015',
      firstname: 'Olivia',
      lastname: 'Scott',
      gender: 'Female',
      isAdmin: false,
      isFormTeacher: false,
      assigned_subjects: ['Igbo', 'Yoruba'],
      class: ['JSS1', 'JSS2'],
      address: '112 Cedar St',
      dob: '1989-10-15',
      mobile_no: '08012345615',
      email: 'olivia.scott@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      id: 'T016',
      firstname: 'Paul',
      lastname: 'Green',
      gender: 'Male',
      isAdmin: false,
      isFormTeacher: false,
      assigned_subjects: ['Christian Religious Studies', 'Government'],
      class: ['SS1', 'SS2'],
      address: '113 Oak St',
      dob: '1977-08-18',
      mobile_no: '08012345616',
      email: 'paul.green@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      id: 'T017',
      firstname: 'Quinn',
      lastname: 'Adams',
      gender: 'Female',
      isAdmin: false,
      isFormTeacher: false,
      assigned_subjects: ['Islamic Religious Studies'],
      class: ['SS2'],
      address: '114 Maple St',
      dob: '1974-12-12',
      mobile_no: '08012345617',
      email: 'quinn.adams@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      id: 'T018',
      firstname: 'Rachel',
      lastname: 'Baker',
      gender: 'Female',
      isAdmin: false,
      isFormTeacher: false,
      assigned_subjects: ['Civic', 'Computer'],
      class: ['SS3', 'JSS3'],
      address: '114 Maple St',
      dob: '1986-12-12',
      mobile_no: '08012345618',
      email: 'rachel.baker@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      id: 'T018',
      firstname: 'Rachel',
      lastname: 'Baker',
      gender: 'Female',
      isAdmin: false,
      isFormTeacher: false,
      assigned_subjects: ['Civic', 'Computer'],
      class: ['SS3', 'JSS1'],
      address: '114 Maple St',
      dob: '1986-12-12',
      mobile_no: '08012345618',
      email: 'rachel.baker@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      id: 'T019',
      firstname: 'Samuel',
      lastname: 'Harris',
      gender: 'Male',
      isAdmin: false,
      isFormTeacher: false,
      assigned_subjects: ['Economics', 'Commerce'],
      class: ['SS2', 'SS3'],
      address: '115 Birch St',
      dob: '1982-05-21',
      mobile_no: '08012345619',
      email: 'samuel.harris@example.com',
    },
    {
      img: 'https://cdn.quasar.dev/img/avatar4.jpg',
      id: 'T020',
      firstname: 'Tina',
      lastname: 'Carter',
      gender: 'Female',
      isAdmin: false,
      isFormTeacher: false,
      assigned_subjects: ['English'],
      class: ['JSS3'],
      address: '116 Cedar St',
      dob: '1978-03-03',
      mobile_no: '08012345620',
      email: 'tina.carter@example.com',
    },
  ]);

  const search_for_teacher = (searchForm: any) => {
    console.log(searchForm);
    return teachers.value.filter(
      (teacher) =>
        searchForm.subject == null ||
        (teacher.assigned_subjects?.includes(searchForm.subject) &&
          searchForm.isFormTeacher == null) ||
        (teacher.isFormTeacher == searchForm.isFormTeacher &&
          searchForm.isAdmin == null) ||
        teacher.isAdmin == searchForm.isAdmin
    );
  };

  const get_teacher_or_404 = (id: string) => {
    return teachers.value.find((teacher) => (teacher.id = id)) ?? '404';
  };
  return {
    teachers,
    search_for_teacher,
    get_teacher_or_404,
  };
});
